name: graft
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch>=2.0.0
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.4
  - nvidia::cuda-toolkit=12.4
  - conda-forge::faiss-gpu
  - pip
  - pip:
      - transformers>=4.30.0
      - accelerate>=0.20.0
      - datasets>=2.16.0,<4.0.0
      - torch-geometric>=2.3.0
      - pyyaml>=6.0
      - numpy>=1.24.0,<2.0.0
      - scikit-learn>=1.2.0
      - tqdm>=4.65.0
      - wandb>=0.15.0
      - colorama
      - matplotlib
      - -e .
