name: graft
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - pip
  - pip:
      - transformers>=4.30.0
      - accelerate>=0.20.0
      - datasets>=2.12.0
      - torch-geometric>=2.3.0
      - faiss-cpu>=1.7.4
      - pyyaml>=6.0
      - numpy>=1.24.0
      - scikit-learn>=1.2.0
      - tqdm>=4.65.0
      - wandb>=0.15.0
      - -e .
